import 'dart:convert';
import 'package:ds_standard_features/ds_standard_features.dart' as http;

/// A service for completing WebAuthn authentication by verifying credential assertions.
///
/// This class handles the second step of WebAuthn authentication by verifying
/// the cryptographic assertion generated by the user's authenticator device.
///
/// ## Security Considerations
/// - Verifies cryptographic signatures server-side
/// - Validates challenge anti-replay protection
/// - Checks credential registration state
/// - Should be used with HTTPS only
///
/// ## Flow Overview
/// 1. Client receives challenge from start endpoint
/// 2. Browser generates assertion using navigator.credentials.get()
/// 3. Client submits assertion to this endpoint for verification
class AortemTransmitAuthenticateWebAuthnCredential {
  /// The API key used for authentication
  final String apiKey;

  /// The base URL for the WebAuthn API endpoints
  final String baseUrl;

  /// The HTTP client instance used for requests
  final http.Client _client;

  /// Creates a WebAuthn credential verifier instance
  ///
  /// [apiKey]: Required API key for authentication
  /// [baseUrl]: Required base URL for the API endpoints
  /// [client]: Optional HTTP client for testing or customization
  AortemTransmitAuthenticateWebAuthnCredential({
    required this.apiKey,
    required this.baseUrl,
    http.Client? client,
  }) : _client = client ?? http.Client();

  /// Verifies a WebAuthn authentication assertion and returns tokens
  ///
  /// This validates the cryptographic signature and completes the WebAuthn
  /// authentication ceremony if successful.
  ///
  /// Parameters:
  /// [credentialResponse]: The WebAuthn assertion response containing:
  ///   - `id`: Base64URL-encoded credential ID
  ///   - `rawId`: Raw credential ID
  ///   - `type`: PublicKeyCredential type
  ///   - `response`: AuthenticatorAssertionResponse containing:
  ///     - `clientDataJSON`: Collected client data
  ///     - `authenticatorData`: Authenticator data
  ///     - `signature`: Cryptographic signature
  ///     - `userHandle`: User handle (optional)
  ///
  /// Returns:
  /// A [Future] that resolves to a Map containing:
  /// - `access_token`: Bearer token for API access
  /// - `id_token`: JWT containing user identity claims
  /// - `refresh_token`: Token for obtaining new access tokens
  /// - `expires_in`: Token validity duration in seconds
  ///
  /// Throws:
  /// - [ArgumentError] if credentialResponse is empty
  /// - [Exception] if verification fails (contains status and error details)
  Future<Map<String, dynamic>> call({
    required Map<String, dynamic> credentialResponse,
  }) async {
    // Validate input parameters
    if (credentialResponse.isEmpty) {
      throw ArgumentError('Credential response cannot be empty');
    }

    try {
      final url = Uri.parse('$baseUrl/v1/auth/webauthn/authenticate/finish');

      final response = await _client.post(
        url,
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer $apiKey',
          'X-Request-ID': DateTime.now().millisecondsSinceEpoch.toString(),
        },
        body: jsonEncode(credentialResponse),
      );

      if (response.statusCode == 200) {
        return jsonDecode(response.body) as Map<String, dynamic>;
      } else {
        throw _createVerificationException(response);
      }
    } on FormatException catch (e) {
      throw Exception('Failed to parse API response: ${e.message}');
    } on http.ClientException catch (e) {
      throw Exception(
        'Network error during credential verification: ${e.message}',
      );
    }
  }

  /// Creates a detailed exception from verification failures
  Exception _createVerificationException(http.Response response) {
    try {
      final error = jsonDecode(response.body) as Map<String, dynamic>;
      return Exception(
        'WebAuthn verification failed (${response.statusCode}): '
        '${error['error'] ?? 'Unknown error'} - '
        '${error['error_description'] ?? response.body}',
      );
    } on FormatException {
      return Exception(
        'WebAuthn verification failed (${response.statusCode}): ${response.body}',
      );
    }
  }
}
