import 'dart:convert';
import 'package:ds_standard_features/ds_standard_features.dart' as http;

/// A service for authenticating users using Time-based One-Time Passwords (TOTP)
/// via Transmit Security's API.
///
/// This class handles the verification of TOTP codes by communicating with
/// Transmit Security's authentication endpoint. It supports both production
/// and testing environments through dependency injection.
///
/// ## Features
/// - Validates TOTP codes against user identifiers
/// - Returns authentication tokens upon successful verification
/// - Includes a stub implementation for testing
///
/// ## Example Usage
/// ```dart
/// final totpService = AortemTransmitAuthenticateTOTP(
///   apiKey: 'your-api-key-here',
///   baseUrl: 'https://api.transmitsecurity.com',
/// );
///
/// try {
///   final authResult = await totpService.authenticateTOTP(
///     identifier: 'user@example.com',
///     totpCode: '123456',
///   );
///   print('Authentication successful: ${authResult['access_token']}');
/// } catch (e) {
///   print('Authentication failed: $e');
/// }
/// ```
class AortemTransmitAuthenticateTOTP {
  /// The API key used for authenticating with Transmit Security's services.
  ///
  /// This key must be kept secure and should not be exposed in client-side code.
  /// The constructor will throw an [ArgumentError] if this is empty.
  final String apiKey;

  /// The base URL for the TOTP authentication endpoint.
  ///
  /// Typically points to Transmit Security's API (e.g., 'https://api.transmitsecurity.com').
  /// Can be customized for different environments or testing.
  final String baseUrl;

  /// The HTTP client used for making requests.
  ///
  /// Uses a default client if none is provided, allowing for dependency injection
  /// during testing.
  final http.Client httpClient;

  /// Creates a TOTP authentication service instance.
  ///
  /// ## Parameters
  /// - [apiKey]: Required API key for authentication (must not be empty)
  /// - [baseUrl]: Required base URL for the API endpoint
  /// - [httpClient]: Optional HTTP client (uses default if not provided)
  ///
  /// ## Throws
  /// - [ArgumentError] if apiKey is empty
  AortemTransmitAuthenticateTOTP({
    required this.apiKey,
    required this.baseUrl,
    http.Client? httpClient,
  }) : httpClient = httpClient ?? http.Client() {
    if (apiKey.isEmpty) {
      throw ArgumentError('API key cannot be empty.');
    }
  }

  /// Authenticates a user using a Time-based One-Time Password (TOTP).
  ///
  /// This method verifies the provided TOTP code against the user's identifier
  /// (typically email or user ID) and returns authentication tokens if successful.
  ///
  /// ## Parameters
  /// - [identifier]: The user's unique identifier (email, phone number, etc.)
  /// - [totpCode]: The 6-8 digit TOTP code generated by the authenticator app
  ///
  /// ## Returns
  /// A [Future] that resolves to a [Map] containing:
  /// - `access_token`: Bearer token for API authorization
  /// - `id_token`: JWT containing user identity claims
  /// - `refresh_token`: Token for obtaining new access tokens
  /// - `token_type`: Typically "Bearer"
  /// - `expires_in`: Token validity duration in seconds
  ///
  /// ## Throws
  /// - [ArgumentError] if identifier or totpCode are empty
  /// - [Exception] if authentication fails (contains status code and error details)
  Future<Map<String, dynamic>> authenticateTOTP({
    required String identifier,
    required String totpCode,
  }) async {
    if (identifier.isEmpty) {
      throw ArgumentError('Identifier cannot be empty.');
    }
    if (totpCode.isEmpty) {
      throw ArgumentError('TOTP code cannot be empty.');
    }

    final url = Uri.parse('$baseUrl/backend-one-time-login/authenticateTOTP');

    final body = json.encode({'identifier': identifier, 'passcode': totpCode});

    final response = await httpClient.post(
      url,
      headers: {
        'Authorization': 'Bearer $apiKey',
        'Content-Type': 'application/json',
      },
      body: body,
    );

    if (response.statusCode == 200) {
      return json.decode(response.body) as Map<String, dynamic>;
    } else {
      throw Exception(
        'Authenticate TOTP failed: ${response.statusCode} ${response.body}',
      );
    }
  }

  /// Stub implementation for testing TOTP authentication.
  ///
  /// This method simulates the authentication flow without making actual API calls,
  /// making it ideal for unit tests and local development.
  ///
  /// ## Parameters
  /// - [identifier]: The user identifier (must not be empty)
  /// - [totpCode]: The TOTP code (must not be empty)
  ///
  /// ## Returns
  /// A [Future] that resolves after a short delay with mock authentication data:
  /// - `access_token`: 'dummy-access-token'
  /// - `id_token`: 'dummy-id-token'
  /// - `refresh_token`: 'dummy-refresh-token'
  /// - `token_type`: 'Bearer'
  /// - `expires_in`: 3600 (1 hour)
  /// - `message`: Success confirmation message
  ///
  /// ## Throws
  /// - [ArgumentError] if identifier or totpCode are empty
  Future<Map<String, dynamic>> authenticateTOTPStub({
    required String identifier,
    required String totpCode,
  }) async {
    if (identifier.isEmpty) {
      throw ArgumentError('Identifier cannot be empty.');
    }
    if (totpCode.isEmpty) {
      throw ArgumentError('TOTP code cannot be empty.');
    }

    // Simulate network latency
    await Future.delayed(const Duration(milliseconds: 100));

    return {
      'access_token': 'dummy-access-token',
      'id_token': 'dummy-id-token',
      'refresh_token': 'dummy-refresh-token',
      'token_type': 'Bearer',
      'expires_in': 3600,
      'message': 'TOTP authentication successful (stub).',
    };
  }
}
